@startuml
annotation java.lang.Override
annotation javax.persistence.Basic
annotation javax.persistence.Entity
annotation javax.persistence.GeneratedValue
annotation javax.persistence.Id
annotation javax.persistence.Temporal
class com.mycompany.Controller.ConexionBD
class com.mycompany.Controller.ConsultaEvento
class com.mycompany.Controller.EjecutarJPA
class com.mycompany.Controller.EnvioCorreos
class com.mycompany.Controller.Evento
class com.mycompany.Controller.Funcionario
class com.mycompany.Controller.Paquete
class com.mycompany.Controller.ServletPlannetPro
class com.mycompany.Controller.Usuario
class com.mycompany.Controller.UsuarioDAO
class com.mycompany.Controller.UsuarioPlannetPro
class com.mycompany.Controller.createEventoServ
class com.mycompany.Controller.usuarios
class jakarta.persistence.EntityManager
class jakarta.persistence.EntityManagerFactory
class jakarta.persistence.Persistence
class jakarta.persistence.TypedQuery
class jakarta.servlet.ServletException
class jakarta.servlet.http.HttpServlet
class jakarta.servlet.http.HttpServletRequest
class jakarta.servlet.http.HttpServletResponse
class jakarta.servlet.http.HttpSession
class java.io.IOException
class java.io.PrintWriter
class java.lang.System
class java.sql.Connection
class java.sql.DriverManager
class java.sql.PreparedStatement
class java.sql.ResultSet
class java.sql.SQLException
class java.util.ArrayList
class java.util.Date
class java.util.List
class java.util.Properties
class java.util.logging.Level
class java.util.logging.Logger
class javax.mail.Message
class javax.mail.MessagingException
class javax.mail.NoSuchProviderException
class javax.mail.Session
class javax.mail.Transport
class javax.mail.internet.AddressException
class javax.mail.internet.InternetAddress
class javax.mail.internet.MimeMessage
class javax.persistence.GenerationType
class javax.persistence.TemporalType
class org.asynchttpclient.Dsl
interface com.mycompany.Controller.validarUsuario
interface java.io.Serializable
com.mycompany.Controller.ConexionBD ..> java.sql.Connection
com.mycompany.Controller.ConexionBD ..> java.sql.DriverManager
com.mycompany.Controller.ConexionBD ..> java.sql.SQLException
com.mycompany.Controller.ConsultaEvento ..> jakarta.persistence.EntityManager
com.mycompany.Controller.ConsultaEvento ..> jakarta.persistence.EntityManagerFactory
com.mycompany.Controller.ConsultaEvento ..> jakarta.persistence.Persistence
com.mycompany.Controller.ConsultaEvento ..> jakarta.persistence.TypedQuery
com.mycompany.Controller.ConsultaEvento ..> java.sql.Connection
com.mycompany.Controller.ConsultaEvento ..> java.sql.PreparedStatement
com.mycompany.Controller.ConsultaEvento ..> java.sql.ResultSet
com.mycompany.Controller.ConsultaEvento ..> java.sql.SQLException
com.mycompany.Controller.ConsultaEvento ..> java.util.ArrayList
com.mycompany.Controller.ConsultaEvento ..> java.util.List
com.mycompany.Controller.EjecutarJPA ..> com.mycompany.Controller.Usuario
com.mycompany.Controller.EjecutarJPA ..> java.sql.Connection
com.mycompany.Controller.EjecutarJPA ..> java.sql.SQLException
com.mycompany.Controller.EnvioCorreos ..> java.util.Properties
com.mycompany.Controller.EnvioCorreos ..> javax.mail.Session
com.mycompany.Controller.EnvioCorreos ..> javax.mail.internet.MimeMessage
com.mycompany.Controller.Evento ..> java.lang.Override
com.mycompany.Controller.Evento ..> javax.persistence.Basic
com.mycompany.Controller.Evento ..> javax.persistence.Entity
com.mycompany.Controller.Evento ..> javax.persistence.GeneratedValue
com.mycompany.Controller.Evento ..> javax.persistence.Id
com.mycompany.Controller.Evento ..> javax.persistence.Temporal
com.mycompany.Controller.Evento ..> java.util.Date
com.mycompany.Controller.Evento ..> javax.persistence.GenerationType
com.mycompany.Controller.Evento ..> javax.persistence.TemporalType
com.mycompany.Controller.Evento --|> java.io.Serializable
com.mycompany.Controller.Funcionario ..> javax.persistence.Basic
com.mycompany.Controller.Funcionario ..> javax.persistence.Entity
com.mycompany.Controller.Funcionario ..> javax.persistence.GeneratedValue
com.mycompany.Controller.Funcionario ..> javax.persistence.Id
com.mycompany.Controller.Funcionario ..> javax.persistence.GenerationType
com.mycompany.Controller.Funcionario --|> java.io.Serializable
com.mycompany.Controller.Paquete ..> javax.persistence.Basic
com.mycompany.Controller.Paquete ..> javax.persistence.Entity
com.mycompany.Controller.Paquete ..> javax.persistence.GeneratedValue
com.mycompany.Controller.Paquete ..> javax.persistence.Id
com.mycompany.Controller.Paquete ..> javax.persistence.GenerationType
com.mycompany.Controller.Paquete --|> java.io.Serializable
com.mycompany.Controller.ServletPlannetPro ..> java.lang.Override
com.mycompany.Controller.ServletPlannetPro ..> jakarta.servlet.ServletException
com.mycompany.Controller.ServletPlannetPro --|> jakarta.servlet.http.HttpServlet
com.mycompany.Controller.ServletPlannetPro ..> jakarta.servlet.http.HttpServletRequest
com.mycompany.Controller.ServletPlannetPro ..> jakarta.servlet.http.HttpServletResponse
com.mycompany.Controller.ServletPlannetPro ..> java.io.IOException
com.mycompany.Controller.ServletPlannetPro ..> java.lang.System
com.mycompany.Controller.ServletPlannetPro ..> java.sql.Connection
com.mycompany.Controller.ServletPlannetPro ..> java.sql.PreparedStatement
com.mycompany.Controller.ServletPlannetPro ..> java.sql.ResultSet
com.mycompany.Controller.ServletPlannetPro ..> java.sql.SQLException
com.mycompany.Controller.ServletPlannetPro ..> java.util.Properties
com.mycompany.Controller.ServletPlannetPro ..> java.util.logging.Level
com.mycompany.Controller.ServletPlannetPro ..> java.util.logging.Logger
com.mycompany.Controller.ServletPlannetPro ..> javax.mail.Message
com.mycompany.Controller.ServletPlannetPro ..> javax.mail.MessagingException
com.mycompany.Controller.ServletPlannetPro ..> javax.mail.NoSuchProviderException
com.mycompany.Controller.ServletPlannetPro ..> javax.mail.Session
com.mycompany.Controller.ServletPlannetPro ..> javax.mail.Transport
com.mycompany.Controller.ServletPlannetPro ..> javax.mail.internet.AddressException
com.mycompany.Controller.ServletPlannetPro ..> javax.mail.internet.InternetAddress
com.mycompany.Controller.ServletPlannetPro ..> javax.mail.internet.MimeMessage
com.mycompany.Controller.Usuario ..> javax.persistence.Basic
com.mycompany.Controller.Usuario ..> javax.persistence.Entity
com.mycompany.Controller.Usuario ..> javax.persistence.GeneratedValue
com.mycompany.Controller.Usuario ..> javax.persistence.Id
com.mycompany.Controller.Usuario ..> javax.persistence.GenerationType
com.mycompany.Controller.Usuario --|> java.io.Serializable
com.mycompany.Controller.UsuarioDAO ..> java.lang.Override
com.mycompany.Controller.UsuarioDAO ..> java.sql.Connection
com.mycompany.Controller.UsuarioDAO ..> java.sql.PreparedStatement
com.mycompany.Controller.UsuarioDAO ..> java.sql.ResultSet
com.mycompany.Controller.UsuarioDAO ..> java.sql.SQLException
com.mycompany.Controller.UsuarioDAO --|> com.mycompany.Controller.validarUsuario
com.mycompany.Controller.UsuarioPlannetPro ..> java.lang.Override
com.mycompany.Controller.UsuarioPlannetPro ..> com.mycompany.Controller.ConsultaEvento
com.mycompany.Controller.UsuarioPlannetPro ..> jakarta.servlet.ServletException
com.mycompany.Controller.UsuarioPlannetPro --|> jakarta.servlet.http.HttpServlet
com.mycompany.Controller.UsuarioPlannetPro ..> jakarta.servlet.http.HttpServletRequest
com.mycompany.Controller.UsuarioPlannetPro ..> jakarta.servlet.http.HttpServletResponse
com.mycompany.Controller.UsuarioPlannetPro ..> jakarta.servlet.http.HttpSession
com.mycompany.Controller.UsuarioPlannetPro ..> java.io.IOException
com.mycompany.Controller.UsuarioPlannetPro ..> java.io.PrintWriter
com.mycompany.Controller.UsuarioPlannetPro ..> java.util.List
com.mycompany.Controller.createEventoServ ..> java.lang.Override
com.mycompany.Controller.createEventoServ ..> jakarta.servlet.ServletException
com.mycompany.Controller.createEventoServ --|> jakarta.servlet.http.HttpServlet
com.mycompany.Controller.createEventoServ ..> jakarta.servlet.http.HttpServletRequest
com.mycompany.Controller.createEventoServ ..> jakarta.servlet.http.HttpServletResponse
com.mycompany.Controller.createEventoServ ..> jakarta.servlet.http.HttpSession
com.mycompany.Controller.createEventoServ ..> java.io.IOException
com.mycompany.Controller.createEventoServ ..> java.lang.System
com.mycompany.Controller.createEventoServ ..> java.sql.Connection
com.mycompany.Controller.createEventoServ ..> java.sql.PreparedStatement
com.mycompany.Controller.createEventoServ ..> java.sql.SQLException
com.mycompany.Controller.createEventoServ ..> org.asynchttpclient.Dsl
@enduml